radars:
- frequency_params:
    frequency: 15000000000.0
  frequency_type: fixed
  lobe_pattern:
    main_lobe_opening_angle: 5.0
    radar_power_at_back_lobe: -20.0
    radar_power_at_main_lobe: 0.0
    type: Sinc
  name: Radar1
  power: 1000.0
  pri_params:
    pri: 0.001
  pri_type: fixed
  pulse_width_params:
    pulse_width: 1.0e-06
  pulse_width_type: fixed
  rotation_params:
    T_rot: 2.5
    alpha0: 0.0
    t0: 0.0
  rotation_type: constant
  start_position:
  - 0
  - 0
  start_time: 0.0
  velocity:
  - 0
  - 0
- frequency_params:
    frequency: 15000000000.0
  frequency_type: fixed
  lobe_pattern:
    main_lobe_opening_angle: 5.0
    radar_power_at_back_lobe: -20.0
    radar_power_at_main_lobe: 0.0
    type: Sinc
  name: Radar2
  power: 1000.0
  pri_params:
    pri: 0.001
  pri_type: fixed
  pulse_width_params:
    pulse_width: 1.0e-06
  pulse_width_type: fixed
  rotation_params:
    T_rot: 2.5
    alpha0: 0.0
    t0: 0.0
  rotation_type: constant
  start_position:
  - 0
  - 0
  start_time: 0.0
  velocity:
  - 0
  - 0
- frequency_params:
    frequency: 15000000000.0
  frequency_type: fixed
  lobe_pattern:
    main_lobe_opening_angle: 5.0
    radar_power_at_back_lobe: -20.0
    radar_power_at_main_lobe: 0.0
    type: Sinc
  name: Radar3
  power: 1000.0
  pri_params:
    pri: 0.001
  pri_type: fixed
  pulse_width_params:
    pulse_width: 1.0e-06
  pulse_width_type: fixed
  rotation_params:
    T_rot: 2.5
    alpha0: 0.0
    t0: 0.0
  rotation_type: constant
  start_position:
  - 0
  - 0
  start_time: 0.0
  velocity:
  - 0
  - 0
- frequency_params:
    frequency: 15000000000.0
  frequency_type: fixed
  lobe_pattern:
    main_lobe_opening_angle: 5.0
    radar_power_at_back_lobe: -20.0
    radar_power_at_main_lobe: 0.0
    type: Sinc
  name: Radar4
  power: 1000.0
  pri_params:
    pri: 0.001
  pri_type: fixed
  pulse_width_params:
    pulse_width: 1.0e-06
  pulse_width_type: fixed
  rotation_params:
    T_rot: 2.5
    alpha0: 0.0
    t0: 0.0
  rotation_type: constant
  start_position:
  - 0
  - 0
  start_time: 0.0
  velocity:
  - 0
  - 0
scenario:
  end_time: 10.0
  start_time: 0.0
  time_step: 0.1
sensors:
- amplitude_error:
    arbitrary:
      error: 0.5 dB
      type: gaussian
    systematic:
      error: 0 dB
      type: constant
  aoa_error:
    arbitrary:
      error: 1 deg
      type: gaussian
    systematic:
      error: 0 deg
      type: constant
  detection_probability:
    level:
    - -80
    - -85
    - -90
    - -95
    probability:
    - 100
    - 85
    - 60
    - 30
  freq_padding_factor: 4
  frequency_error:
    arbitrary:
      error: 1e6 Hz
      type: gaussian
    systematic:
      error: 0 Hz
      rate: 100 Hz/s
      type: linear
  name: Sensor1
  pulse_width_error:
    arbitrary:
      error: 2%
      type: uniform
    systematic:
      error: 0 s
      type: constant
  saturation_level: -70 dB
  start_position:
  - 0
  - 0
  start_time: 0.0
  toa_error:
    arbitrary:
      error: 1e-9 s
      type: gaussian
    systematic:
      error: 0 s
      type: constant
  velocity:
  - 0
  - 0
