radars:
- frequency_params:
    frequency: 500000000.0
  frequency_type: fixed
  lobe_pattern:
    main_lobe_opening_angle: 5.0
    radar_power_at_back_lobe: -20.0
    radar_power_at_main_lobe: 0.0
    type: Sinc
  name: Radar1
  power: 0.001
  pri_params:
    jitter_percentage: 5.0
    mean_pri: 0.001
    pri: 0.001
  pri_type: jitter
  pulse_width_params:
    pulse_width: 0.0001
  pulse_width_type: fixed
  rotation_params:
    A: 0.1
    T_rot: 2.5
    alpha0: 0.0
    phi0: 0.0
    s: 1.0
    t0: 0.0
  rotation_type: varying
  start_position:
  - 0
  - 0
  start_time: 0.0
  velocity:
  - 0
  - 0
- frequency_params:
    frequency: 2500000000.0
  frequency_type: fixed
  lobe_pattern:
    main_lobe_opening_angle: 4.0
    radar_power_at_back_lobe: -22.0
    radar_power_at_main_lobe: 0.0
    type: Sinc
  name: Radar2
  power: 0.000316
  pri_params:
    pri_pattern:
    - 0.001
    - 0.0012
    - 0.0011
    - 0.0013
  pri_type: stagger
  pulse_width_params:
    pulse_width: 0.0002
  pulse_width_type: fixed
  rotation_params:
    T_rot: 3.0
    alpha0: 0.0
    t0: 0.0
  rotation_type: constant
  start_position:
  - 1000
  - 1000
  start_time: 0.0
  velocity:
  - 0
  - 0
- frequency_params:
    frequency_pattern:
    - 4.5e9
    - 4.504e9
    - 4.508e9
    repetitions:
    - 3
    - 3
    - 3
  frequency_type: switched
  lobe_pattern:
    main_lobe_opening_angle: 6.0
    radar_power_at_back_lobe: -18.0
    radar_power_at_main_lobe: 0.0
    type: Sinc
  name: Radar3
  power: 1.0e-05
  pri_params:
    jitter_percentage: 5.0
    mean_pri: 0.001
  pri_type: jitter
  pulse_width_params:
    pulse_width_pattern:
    - 0.0003
    - 0.00032
    - 0.00034
  pulse_width_type: stagger
  rotation_params:
    T_rot: 2.8
    alpha0: 0.0
    t0: 0.0
  rotation_type: constant
  start_position:
  - -500
  - 500
  start_time: 0.0
  velocity:
  - 0
  - 0
- frequency_params:
    frequency: 6500000000.0
  frequency_type: fixed
  lobe_pattern:
    main_lobe_opening_angle: 5.0
    radar_power_at_back_lobe: -20.0
    radar_power_at_main_lobe: 0.0
    type: Sinc
  name: Radar4
  power: 1.0e-07
  pri_params:
    jitter_percentage: 5.0
    mean_pri: 0.0008
    pri: 0.0008
  pri_type: jitter
  pulse_width_params:
    pulse_width: 0.0004
  pulse_width_type: fixed
  rotation_params:
    A: 0.1
    T_rot: 2.5
    alpha0: 0.0
    phi0: 0.0
    s: 1.0
    t0: 0.0
  rotation_type: varying
  start_position:
  - 0
  - 100
  start_time: 1.0
  velocity:
  - 1
  - 0
- frequency_params:
    frequency: 8500000000.0
  frequency_type: fixed
  lobe_pattern:
    main_lobe_opening_angle: 5.0
    radar_power_at_back_lobe: -20.0
    radar_power_at_main_lobe: 0.0
    type: Sinc
  name: Radar5
  power: 3.16e-08
  pri_params:
    pri_pattern:
    - 0.0015
    - 0.0016
    - 0.0014
  pri_type: stagger
  pulse_width_params:
    pulse_width: 0.0005
  pulse_width_type: fixed
  rotation_params:
    T_rot: 3.5
    alpha0: 0.0
    t0: 0.0
  rotation_type: constant
  start_position:
  - 200
  - 200
  start_time: 2.0
  velocity:
  - 0
  - 0
- frequency_params:
    frequency: 10500000000.0
  frequency_type: fixed
  lobe_pattern:
    main_lobe_opening_angle: 5.0
    radar_power_at_back_lobe: -20.0
    radar_power_at_main_lobe: 0.0
    type: Sinc
  name: Radar6
  power: 0.0001
  pri_params:
    pri_pattern:
    - 0.0009
    - 0.0011
  pri_type: stagger
  pulse_width_params:
    pulse_width: 0.00015
  pulse_width_type: fixed
  rotation_params:
    A: 0.0
    T_rot: 3.0
    alpha0: 45.0
    phi0: 0.0
    s: 2.0
    t0: 0.0
  rotation_type: varying
  start_position:
  - 300
  - 300
  start_time: 1.0
  velocity:
  - 0
  - 0
scenario:
  end_time: 10.0
  start_time: 0.0
  time_step: 0.01
sensors:
- amplitude_error:
    arbitrary:
      error: 1.5 dB
      type: uniform
    systematic:
      error: 0 dB
      type: constant
  aoa_error:
    arbitrary:
      error: 0 deg
      type: constant
    systematic:
      error: 0 deg
      type: constant
  detection_probability:
    level:
    - -80
    - -90
    - -95
    - -100
    probability:
    - 100
    - 80
    - 30
    - 5
  frequency_error:
    arbitrary:
      error: 10e6 Hz
      type: gaussian
    systematic:
      error: 0 Hz
      type: constant
  name: Sensor1
  pulse_width_error:
    arbitrary:
      error: 4.5%
      type: uniform
    systematic:
      error: 0 s
      type: constant
  saturation_level: -70 dB
  start_position:
  - 500
  - 500
  start_time: 2
  toa_error:
    arbitrary:
      error: 1e-9 s
      type: gaussian
    systematic:
      error: 0 s
      type: constant
  velocity:
  - -5
  - 0
